### ISSUE TITLE
Unable to link output file with workflow

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/ChallengeWorkflowTemplates#6]
```
STDERR: 2018-10-09T23:11:23.185027900Z INFO:cwltool:Resolved 'ChallengeWorkflowTemplates-master/dockerAgent_workflow.cwl' to 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/dockerAgent_workflow.cwl'
STDERR: 2018-10-09T23:11:25.868227900Z WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (4).
STDERR: 2018-10-09T23:11:25.868268400Z WARNING:toil.batchSystems.singleMachine:Limiting maxMemory to physically available memory (2095771648).
STDERR: 2018-10-09T23:11:25.870314400Z WARNING:toil.batchSystems.singleMachine:Limiting maxDisk to physically available disk (145839058944).
STDERR: 2018-10-09T23:11:25.912085400Z INFO:toil:Running Toil version 3.18.0-84239d802248a5f4a220e762b3b8ce5cc92af0be.
STDERR: 2018-10-09T23:11:26.748496600Z INFO:toil.leader:Issued job 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/getSubmissionDocker.cwl' python Y/v/jobfTsZWr with job batch system ID: 1 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDERR: 2018-10-09T23:11:26.756122600Z INFO:toil.leader:Issued job 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/getDockerConfig.cwl' python C/a/joblyBFsG with job batch system ID: 2 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDERR: 2018-10-09T23:11:30.095559000Z INFO:toil.leader:Job ended successfully: 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/getDockerConfig.cwl' python C/a/joblyBFsG
STDERR: 2018-10-09T23:11:31.378194200Z INFO:toil.leader:Job ended successfully: 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/getSubmissionDocker.cwl' python Y/v/jobfTsZWr
STDERR: 2018-10-09T23:11:31.379103800Z INFO:toil.leader:Issued job 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/validateDocker.cwl' python Z/A/jobfbQsbj with job batch system ID: 3 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDERR: 2018-10-09T23:11:31.386446700Z INFO:toil.leader:Issued job 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/runDocker.cwl' python z/N/jobmGkM1C with job batch system ID: 4 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDERR: 2018-10-09T23:11:35.606467400Z INFO:toil.leader:Job ended successfully: 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/validateDocker.cwl' python Z/A/jobfbQsbj
STDERR: 2018-10-09T23:11:43.234533100Z INFO:toil.leader:Job ended successfully: 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/runDocker.cwl' python z/N/jobmGkM1C
STDERR: 2018-10-09T23:11:43.235230100Z WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/runDocker.cwl' python z/N/jobmGkM1C
STDERR: 2018-10-09T23:11:43.235329600Z WARNING:toil.leader:z/N/jobmGkM1C    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
STDERR: 2018-10-09T23:11:43.235405100Z WARNING:toil.leader:z/N/jobmGkM1C    INFO:toil:Running Toil version 3.18.0-84239d802248a5f4a220e762b3b8ce5cc92af0be.
STDERR: 2018-10-09T23:11:43.235575700Z WARNING:toil.leader:z/N/jobmGkM1C    [job runDocker.cwl] /tmp/tmpEGer5j/a/a/out_tmpdiriEuCz0$ python \
STDERR: 2018-10-09T23:11:43.235594800Z WARNING:toil.leader:z/N/jobmGkM1C        runDocker.py \
STDERR: 2018-10-09T23:11:43.235673200Z WARNING:toil.leader:z/N/jobmGkM1C        -s \
STDERR: 2018-10-09T23:11:43.235927600Z WARNING:toil.leader:z/N/jobmGkM1C        9681550 \
STDERR: 2018-10-09T23:11:43.235954300Z WARNING:toil.leader:z/N/jobmGkM1C        -p \
STDERR: 2018-10-09T23:11:43.235966300Z WARNING:toil.leader:z/N/jobmGkM1C        docker.synapse.org/syn4990358/testwf \
STDERR: 2018-10-09T23:11:43.235982900Z WARNING:toil.leader:z/N/jobmGkM1C        -d \
STDERR: 2018-10-09T23:11:43.236039400Z WARNING:toil.leader:z/N/jobmGkM1C        sha256:9f09e064ba819cfe811bd19b19ff37dd83fa41d0f53926a70bd8f210b3d3371c \
STDERR: 2018-10-09T23:11:43.236283100Z WARNING:toil.leader:z/N/jobmGkM1C        -i \
STDERR: 2018-10-09T23:11:43.236310700Z WARNING:toil.leader:z/N/jobmGkM1C        /Users/ThomasY/sandbox \
STDERR: 2018-10-09T23:11:43.236326800Z WARNING:toil.leader:z/N/jobmGkM1C        -o \
STDERR: 2018-10-09T23:11:43.236419200Z WARNING:toil.leader:z/N/jobmGkM1C        /tmp/tmpEGer5j/a/a/out_tmpdiriEuCz0
STDERR: 2018-10-09T23:11:43.236537600Z WARNING:toil.leader:z/N/jobmGkM1C    INFO:cwltool:[job runDocker.cwl] /tmp/tmpEGer5j/a/a/out_tmpdiriEuCz0$ python \
STDERR: 2018-10-09T23:11:43.236553000Z WARNING:toil.leader:z/N/jobmGkM1C        runDocker.py \
STDERR: 2018-10-09T23:11:43.236651600Z WARNING:toil.leader:z/N/jobmGkM1C        -s \
STDERR: 2018-10-09T23:11:43.236680800Z WARNING:toil.leader:z/N/jobmGkM1C        9681550 \
STDERR: 2018-10-09T23:11:43.236851000Z WARNING:toil.leader:z/N/jobmGkM1C        -p \
STDERR: 2018-10-09T23:11:43.236897600Z WARNING:toil.leader:z/N/jobmGkM1C        docker.synapse.org/syn4990358/testwf \
STDERR: 2018-10-09T23:11:43.236912400Z WARNING:toil.leader:z/N/jobmGkM1C        -d \
STDERR: 2018-10-09T23:11:43.236974600Z WARNING:toil.leader:z/N/jobmGkM1C        sha256:9f09e064ba819cfe811bd19b19ff37dd83fa41d0f53926a70bd8f210b3d3371c \
STDERR: 2018-10-09T23:11:43.237233100Z WARNING:toil.leader:z/N/jobmGkM1C        -i \
STDERR: 2018-10-09T23:11:43.237250200Z WARNING:toil.leader:z/N/jobmGkM1C        /Users/ThomasY/sandbox \
STDERR: 2018-10-09T23:11:43.237461400Z WARNING:toil.leader:z/N/jobmGkM1C        -o \
STDERR: 2018-10-09T23:11:43.237478600Z WARNING:toil.leader:z/N/jobmGkM1C        /tmp/tmpEGer5j/a/a/out_tmpdiriEuCz0
STDERR: 2018-10-09T23:11:43.237489000Z WARNING:toil.leader:z/N/jobmGkM1C    finished
STDERR: 2018-10-09T23:11:43.237575800Z WARNING:toil.leader:z/N/jobmGkM1C    [job runDocker.cwl] Job error:
STDERR: 2018-10-09T23:11:43.237591400Z WARNING:toil.leader:z/N/jobmGkM1C    Error collecting output for parameter 'predictions':
STDERR: 2018-10-09T23:11:43.237795700Z WARNING:toil.leader:z/N/jobmGkM1C    :1:1: Did not find output file with glob pattern: '['/tmp/tmpEGer5j/a/a/out_tmpdiriEuCz0/listOfFiles.csv']'
STDERR: 2018-10-09T23:11:43.237951200Z WARNING:toil.leader:z/N/jobmGkM1C    ERROR:cwltool:[job runDocker.cwl] Job error:
STDERR: 2018-10-09T23:11:43.237975500Z WARNING:toil.leader:z/N/jobmGkM1C    Error collecting output for parameter 'predictions':
STDERR: 2018-10-09T23:11:43.238026400Z WARNING:toil.leader:z/N/jobmGkM1C    :1:1: Did not find output file with glob pattern: '['/tmp/tmpEGer5j/a/a/out_tmpdiriEuCz0/listOfFiles.csv']'
STDERR: 2018-10-09T23:11:43.238047000Z WARNING:toil.leader:z/N/jobmGkM1C    [job runDocker.cwl] completed permanentFail
STDERR: 2018-10-09T23:11:43.238079900Z WARNING:toil.leader:z/N/jobmGkM1C    WARNING:cwltool:[job runDocker.cwl] completed permanentFail
STDERR: 2018-10-09T23:11:43.238100500Z WARNING:toil.leader:z/N/jobmGkM1C    Traceback (most recent call last):
STDERR: 2018-10-09T23:11:43.238268600Z WARNING:toil.leader:z/N/jobmGkM1C      File "/usr/local/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
STDERR: 2018-10-09T23:11:43.238299300Z WARNING:toil.leader:z/N/jobmGkM1C        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
STDERR: 2018-10-09T23:11:43.238365500Z WARNING:toil.leader:z/N/jobmGkM1C      File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
STDERR: 2018-10-09T23:11:43.238388900Z WARNING:toil.leader:z/N/jobmGkM1C        returnValues = self._run(jobGraph, fileStore)
STDERR: 2018-10-09T23:11:43.238607400Z WARNING:toil.leader:z/N/jobmGkM1C      File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1296, in _run
STDERR: 2018-10-09T23:11:43.238635900Z WARNING:toil.leader:z/N/jobmGkM1C        return self.run(fileStore)
STDERR: 2018-10-09T23:11:43.238652400Z WARNING:toil.leader:z/N/jobmGkM1C      File "/usr/local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 567, in run
STDERR: 2018-10-09T23:11:43.238669900Z WARNING:toil.leader:z/N/jobmGkM1C        raise cwltool.errors.WorkflowException(status)
STDERR: 2018-10-09T23:11:43.238689100Z WARNING:toil.leader:z/N/jobmGkM1C    WorkflowException: permanentFail
STDERR: 2018-10-09T23:11:43.238703000Z WARNING:toil.leader:z/N/jobmGkM1C    ERROR:toil.worker:Exiting the worker because of a failed job on host b4ea4919775a
STDERR: 2018-10-09T23:11:43.238854200Z WARNING:toil.leader:z/N/jobmGkM1C    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/runDocker.cwl' python z/N/jobmGkM1C with ID z/N/jobmGkM1C to 0
STDERR: 2018-10-09T23:11:43.239444700Z WARNING:toil.leader:Job 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/runDocker.cwl' python z/N/jobmGkM1C with ID z/N/jobmGkM1C is completely failed
STDERR: 2018-10-09T23:11:49.973568700Z INFO:toil.leader:Finished toil run with 4 failed jobs.
STDERR: 2018-10-09T23:11:49.973616300Z INFO:toil.leader:Failed jobs at end of the run: 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/runDocker.cwl' python z/N/jobmGkM1C 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/getSubmissionDocker.cwl' python Y/v/jobfTsZWr 'CWLWorkflow' 6/V/jobPu7x2T 'file:///Users/ThomasY/sandbox/c14e0248-2869-49ff-9eea-b5442de88ffe/ChallengeWorkflowTemplates-master/getDockerConfig.cwl' python C/a/joblyBFsG
STDERR: 2018-10-09T23:11:49.988956200Z Traceback (most recent call last):
STDERR: 2018-10-09T23:11:49.988994800Z   File "/usr/local/bin/toil-cwl-runner", line 11, in <module>
STDERR: 2018-10-09T23:11:49.989012500Z     sys.exit(main())
STDERR: 2018-10-09T23:11:49.989027400Z   File "/usr/local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 1220, in main
STDERR: 2018-10-09T23:11:49.989274400Z     outobj = toil.start(wf1)
STDERR: 2018-10-09T23:11:49.989304400Z   File "/usr/local/lib/python2.7/site-packages/toil/common.py", line 784, in start
STDERR: 2018-10-09T23:11:49.989443900Z     return self._runMainLoop(rootJobGraph)
STDERR: 2018-10-09T23:11:49.989486200Z   File "/usr/local/lib/python2.7/site-packages/toil/common.py", line 1059, in _runMainLoop
STDERR: 2018-10-09T23:11:49.989790000Z     jobCache=self._jobCache).run()
STDERR: 2018-10-09T23:11:49.989812400Z   File "/usr/local/lib/python2.7/site-packages/toil/leader.py", line 237, in run
STDERR: 2018-10-09T23:11:49.989829900Z     raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
STDERR: 2018-10-09T23:11:49.989971000Z toil.leader.FailedJobsException

```

**Comment by thomasyu888** [comment]
@brucehoff 

I'm not sure why my output isn't binding when I run this workflow with the workflow Hook.  This is the workflow I run: https://github.com/Sage-Bionetworks/ChallengeWorkflowTemplates/blob/master/dockerAgent_workflow.cwl.

When I run this workflow locally with `cwl-runner` it works. Unsure how to proceed.

Also...

```
ls /tmp/tmpEGer5j/a/a/out_tmpdiriEuCz0
listOfFiles.csv
```
which is what I set the outputDir to be in this tool: https://github.com/Sage-Bionetworks/ChallengeWorkflowTemplates/blob/master/runDocker.cwl

**Comment by brucehoff** [comment]
@thomasyu888   Do you have any evidence that the output file was created when container was run via the workflow hook?  That is, do you know that the container (`docker.synapse.org/syn4990358/testwf`) ran at all?

The reason I ask is that I see in your log (above) that one input to your script `runDocker.py` is `/Users/ThomasY/sandbox` which seems like it would be an error.

**Comment by thomasyu888** [comment]
I'm unable to get the output file to be created for some reason, but I also know that the workflow hook does not have access to my local file system.

I did a lot of unsuccessful testing last night with how to get everything mounted and trying to get my output file. I will do more testing today.

**Comment by brucehoff** [comment]
> I'm unable to get the output file to be created for some reason

Yes, my suspicion is that the container isn't running to completion, let alone generating the output file.

> the workflow hook does not have access to my local file system

Yes, the workflow hook runs in a container and only has access to selected directories.

**Comment by brucehoff** [comment]
@thomasyu888 This will not work:
https://github.com/Sage-Bionetworks/ChallengeWorkflowTemplates/blob/master/runDocker.cwl#L47
```
          os.mkdir(args.submissionId)
```
because `runDocker.cwl` itself is running in a container and therefore can't access an arbitrary path on the file system of the host which runs the `docker.synapse.org/syn4990358/testwf` container.

**Comment by brucehoff** [comment]
When we run the workflow hook (as a Docker container) we mount the following:
```
${WORKFLOW_TEMPDIR}:/tempDir:rw
```
(as you can see here: https://github.com/Sage-Bionetworks/SynapseWorkflowHook/blob/master/docker-compose.yaml#L7)

Let's say `WORKFLOW_TEMPDIR` is set (in your `.env` file) to `/home/ubuntu/temp/` and say we run the `SynapseWorkflowExample` workflow.  The hook will download and unzip the repo' into:
`/home/ubuntu/temp/<uuid>/SynapseWorkflowExample-Master/`.  From inside the Workflow Hook container it will look like:
`/tempDir/<uuid>/SynapseWorkflowExample-Master/`.  Now the Workflow Hook will run Toil, with the following volume mount:
```
/home/ubuntu/temp/<uuid>/SynapseWorkflowExample-Master/:/home/ubuntu/temp/<uuid>/SynapseWorkflowExample-Master/
```

That is, we take care to ensure that the path within the working directory, as seen by Toil, is the same as on the host.

So when you launch a container from within a Toil workflow, as long as you mount the working directory (or a sub-folder within the working directory) to your container, you will be mounting a valid path on the host machine to your container.  The mount point in the container must be the same as that on the host.

For example the `os.*` operations seen here: https://github.com/Sage-Bionetworks/ChallengeWorkflowTemplates/blob/master/runDocker.cwl#L49
will only work if they are within the working directory.

**Comment by brucehoff** [comment]
I can repro the problem:  I made a workflow that outputs the current directory:
https://github.com/Sage-Bionetworks/SynapseWorkflowExample/tree/issue-6
It outputs:
```
/tmp/tmpK9qgy_/3/9/out_tmpdirj4Jx0m
```
even though we set the working dir elsewhere.

**Comment by thomasyu888** [comment]
Thanks!

**Comment by brucehoff** [comment]
This seems to have an effect:
https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/279e09018682e61acbb2052f20f4059644b9f5ce

Because now my test script outputs:
```
/Users/bhoff/temp/ee24e2f5-b285-44a9-b874-b25418caf0c3/tmpmeuDix/d/a/out_tmpdirW7lK8l
```
which is what we want Toil to use as the temp dir.

Can you see if it fixes the problem, @thomasyu888 ?
Once the build finishes
https://hub.docker.com/r/sagebionetworks/synapseworkflowhook/builds/
you would update your copy with:
`docker pull sagebionetworks/synapseworkflowhook`

**Comment by thomasyu888** [comment]
I think this works!  Thanks!
